version: '3'

services: 
# apache mikrozerbitzua
  apache:
    container_name: apache
    build: web/
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
# mysql mikrozerbitzua
  mysql:
    container_name: mysql
    build: mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sanjorge
      MYSQL_USER: sanjorge
      MYSQL_PASSWORD: sanjorge
      MYSQL_DATABASE: daw
# phpmyadmin mikrozerbitzua
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 80:80
    environment:
      PMA_HOST: mysql