FROM ubuntu:latest

RUN 	apt-get update \
	&& apt install -y apache2 \
	&& apt install nano \
	a2enmod rewrite \
	a2enmod ssl \
	a2enmod authz_core

COPY index.html /var/www/html/

RUN service apache2 restart

