version: '3'

services:

  apache:
    container_name: apache
    build: apache/
    volumes:
      - ./web:/var/www/html
    ports:
      - "8080:80"

  mysql:
    container_name: mysql
    build: mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sanjorge
      MYSQL_USER: sanjorge
      MYSQL_PASSWORD: sanjorge
      MYSQL_DATABASE: daw

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 80:80
    environment:
      PMA_HOST: mysql